#!/usr/bin/python
# -*- coding: utf-8 -*-

mapping = {
    "Mo Johnston": "Maurice Johnston",
    "Manny Lagos": "Manuel Lagos",
    "Ritchie Kotschau": "Richard Kotschau",
    "Joey DiGiamarino": "Joseph DiGiamarino",
    "Mike Clark": "Michael Clark",
    "Matt Crawford": "Matthew Crawford",
    "Matt Taylor": "Matthew Taylor",
    "Jozy Altidore": "Josmer Altidore",
    "Chris Carrieri": "Christopher Carrieri" ,
    "Clint Dempsey": "Clinton Dempsey",
    "Ricky Lewis": "Eric Lewis",
    "Junior Agogo": "Manuel Agogo",
    "Eddie Johnson": "Edward Johnson",
    "Rod Dyachenko": "Rodion Dyachenko",
    "Joe Vide": "Joseph Vide",
    "Alex Yi": "Alexander Yi",
    "Fred": "Helbert Frederico Carreiro da Silva",
    "Thiago": "Thiago da Rosa Correa",
    "Jose Burciaga Jr.": "Jose Burciaga",
    "Mike Nugent": "Michael Nugent",
    "Dipsy Selolwane": "Diphetogo Selolwane",
    "Dedi Ben Dayan": "David Ben Dayan",
    "Tom McManus": "Thomas McManus",
    "Doctor Khumalo": "Theophilus Khumalo",
    "Tote Castaneda": "Jorge Castaneda",
    "Abbe Ibrahim": "Abdoulaye Ibrahim",
    "Steve Howey": "Stephen Howey",
    "Jamie Holmes": "James Holmes",
    "Marcelo Vega": "Francisco Marcelo Vega",
    "Jeff Moore": "Jeffrey Moore",
    "Toni Nhleko": "Nkosinathi Nhleko",
    "Pat Carroll": "Patrick Carroll",
    "Ricardinho": "Ricardo Alves Pereira",
    "Waldir": "Waldir Saenz",
    "Kasali Yinka Casal": "Kasali Casal",
    "Guido": "Guido Neto",
    "Damian": "Damian Silvera",
    "Billy Sleeth": "William Sleeth",
    "Mandi Urbas": "Hermann Urbas",
    "Kenny Deuchar": "Kenneth Deuchar",
    "Andy Welsh": "Andrew Welsh",
    "Cassio": "Jose de Abreu Oliveira",
    "Isaias Bardales Jr.": "Isaias Bardales",
    "Mike Burke": "Michael Burke",
    "G.R. Cannon": "Garland Cannon",
    "Denilson": "Denilson de Oliveira",
    "Jose Manuel Abundis" : "Jose Abundis",
    "Barry Alvarez": "Byron Alvarez",
    "Marquinho": "Marco Dos Santos",
    "Dejair": "Dejair Ferreira",
    "Branco": "Claudio Vaz Leal",
    "Welton": "Welton Melo",
    "Alvaro Pires": "Álvaro Henrique Alves Pires",
    "Andre Luiz": "André Luiz Moreira",
    "Jair": "Anselmo Ribeiro",
    "Scott Buete": "George Buete",
    "Luis Miguel Escalada": "Luis Escalada",
    "Walter Garcia": "Walter Ariel García",
    
    }

