#!/usr/bin/python
# -*- coding: utf-8 -*-

mapping = {
    "Marvelle Wynne": "Marvell Wynne",
    "Sasha Kljestan": "Sacha Kljestan",
    "Robbie Rodgers": "Robbie Rogers",
    "Kamini Hill": "Kamani Hill",
    "Robbie Findlay": "Robbie Findley",
    "Amechi Agwe": "Amaechi Igwe",
    "Jose Torres": "Jose Francisco Torres",
    "Jose Torres": "Jose Francisco Torres",
    "Jay DeMerit": "Jay Demerit",
    "Steve Lenhart": "Steven Lenhart",
    "Stephen Lenhart": "Steven Lenhart",
    "Pat Ianni": "Patrick Ianni",
    "Nick Labrocca": "Nick LaBrocca",
    "Marcus Hahnneman": "Marcus Hahnemann",
    "Corey Gibbs": "Cory Gibbs",
    "Danny Karbassiyoon": "Daniel Karbassiyoon",
    "Darius Barnes": "Darrius Barnes",
    "Zach Schilawski": "Zack Schilawski",
    "Gabe Ferrari": "Gabriel Ferrari",
    "Amechi Igwe": "Amaechi Igwe",
    "Mike Videira": "Michael Videira",
    "John Van Buskirk": "John van Buskirk",
    "Leighton O'brien": "Leighton O'Brien",
    'Will Hesmer': "William Hesmer",

    "Mo Johnston": "Maurice Johnston",
    "Manny Lagos": "Manuel Lagos",
    "Ritchie Kotschau": "Richard Kotschau",
    "Rich Kotschau": "Richard Kotschau",
    "Joey DiGiamarino": "Joseph DiGiamarino",
    "Mike Clark": "Michael Clark",
    "Matt Crawford": "Matthew Crawford",
    "Matt Taylor": "Matthew Taylor",
    "Jozy Altidore": "Josmer Altidore",
    "Chris Carrieri": "Christopher Carrieri" ,
    "Clint Dempsey": "Clinton Dempsey",
    "Ricky Lewis": "Eric Lewis",
    "Junior Agogo": "Manuel Agogo",
    "Eddie Johnson": "Edward Johnson",
    "Rod Dyachenko": "Rodion Dyachenko",
    "Joe Vide": "Joseph Vide",
    "Alex Yi": "Alexander Yi",
    "Fred": "Helbert Frederico Carreiro da Silva",
    "Thiago": "Thiago da Rosa Correa",
    "Jose Burciaga Jr.": "Jose Burciaga",
    "Brian Namoff": "Bryan Namoff",
    "Mike Nugent": "Michael Nugent",
    "Dipsy Selolwane": "Diphetogo Selolwane",
    "Dedi Ben Dayan": "David Ben Dayan",
    "Tom McManus": "Thomas McManus",
    "Doctor Khumalo": "Theophilus Khumalo",
    "Tote Castaneda": "Jorge Castaneda",
    "Abbe Ibrahim": "Abdoulaye Ibrahim",
    "Steve Howey": "Stephen Howey",
    "Jamie Holmes": "James Holmes",
    "Marcelo Vega": "Francisco Marcelo Vega",
    "Jeff Moore": "Jeffrey Moore",
    "Toni Nhleko": "Nkosinathi Nhleko",
    "Pat Carroll": "Patrick Carroll",
    "Ricardinho": "Ricardo Alves Pereira",
    "Waldir": "Waldir Saenz",
    "Kasali Yinka Casal": "Kasali Casal",
    "Guido": "Guido Neto",
    "Damian": "Damian Silvera",
    "Billy Sleeth": "William Sleeth",
    "Mandi Urbas": "Hermann Urbas",
    "Kenny Deuchar": "Kenneth Deuchar",
    "Andy Welsh": "Andrew Welsh",
    "Cassio": "Jose de Abreu Oliveira",
    "Isaias Bardales Jr.": "Isaias Bardales",
    "Mike Burke": "Michael Burke",
    "G.R. Cannon": "Garland Cannon",
    "Denilson": "Denilson de Oliveira",
    "Jose Manuel Abundis" : "Jose Abundis",
    "Barry Alvarez": "Byron Alvarez",
    "Marquinho": "Marco Dos Santos",
    "Dejair": "Dejair Ferreira",
    "Branco": "Claudio Vaz Leal",
    "Welton": "Welton Melo",
    "Alvaro Pires": "Álvaro Henrique Alves Pires",
    "Andre Luiz": "André Luiz Moreira",
    "Jair": "Anselmo Ribeiro",
    "Scott Buete": "George Buete",
    "Luis Miguel Escalada": "Luis Escalada",
    "Walter Garcia": "Walter Ariel García",
    "DJ Countess": "D.J. Countess",
    "Hristo Stoichkov": "Hristo Stoitchkov",
    "Shaka Hislop": "Neil Hislop",
    "Kwame Watson Sirobie": "Kwame Watson-Sirobie",
    "Brad Guzan": "Bradley Guzan",
    "Claudio Su\xc3\xa1rez": "Claudio Suarez",
    "Jason Hern\xc3\xa1ndez": "Jason Hernandez",
    "Peter Marino": "Pete Marino",
    "Steven Herdsman": "Stephen Herdsman",
    "Brad Friedel": "Bradley Friedel",
    "Tom Dooley": "Thomas Dooley",
    "Dan Popik": "Daniel Popik",
    "Danny O\xe2\x80\x99Rourke": "Danny O'Rourke",
    "Bo Oshoniyi": "Adegboyega Oshoniyi",
    "Jean Phillippe Peguero": "Peguero Jean Philippe",
    "Jean-Phillippe Peguero": "Peguero Jean Philippe",
    "Jean-Philippe Peguero": "Peguero Jean Philippe",
    "Peguero Jean Phillipe": "Peguero Jean Philippe",
    "Peguero Jean Phillippe": "Peguero Jean Philippe",
    "Raimo de Vries": "Raimo De Vries",
    "Nino DaSilva": "Nino Da Silva",
    "Michael Slivinski": "Mike Slivinski",
    "John Michael Hayden": "John Hayden",
    "Tony Caig": "Antony Caig",
    "Zach Wells": "Zachary Wells",
    "Pete Vagenas": "Peter Vagenas",
    "Joey Franchino": "Joe Franchino",
    "Mike Zaher": "Michael Zaher",
    "Brandon Mcdonald": "Brandon McDonald",
    "Maksim Usanov": "Maxim Usanov",
    "Kenny Stamatopoulos": "Kyriakos Stamatopoulos",
    "Joe Addo": "Joseph Addo",
    "Ernst Obster": "Ernst Oebster",
    "Ruben Dario Hernandez": "Ruben Hernandez",
    "Samuel Appiah": "Sammy Appiah",
    "Juan Berthy Suarez": "Juan Suarez",
    "Hong Myung-Bo": "Hong Myung Bo",
    "Juan Manuel Pena": "Juan Pena",
    "Preki Radosavljevic": "Preki",
    "Dan Califf": "Danny Califf",
    "Missael Espinoza": "Eduardo Espinoza",
    "Jose Palacios": "Arley Palacios",
    "Kwame Watson Siriboe": "Kwame Watson-Siriboe",
    "Andrew Williams": "Andy Williams",
    "Josh Gros": "Joshua Gros",
    "Ed Johnson": "Edward Johnson",
    'Ronnie O’Brien': "Ronnie O'Brien",
    'Raimo deVries': "Raimo De Vries",
    'Luis Angel Landin': "Luis Landin",
    'Mike Seamon': "Michael Seamon",
    'José Cancela': "Jose Cancela",
    'Rafa Márquez': "Rafael Marquez",
    'Paulo Araujo': "Paulo Junior",
    'Dedi Ben-Dayan': "David Ben Dayan",
    'Dan Wasson': "Daniel Wasson",
    'Orlando Pérez': "Orlando Perez",
    'Johnnie Garcia': "Johnny Garcia",
    'Rodrigo López': 'Rodrigo Lopez',
    "Mario Ivan Guerrero": "Ivan Guerrero",
    'Fred Carreiro': 'Helbert Frederico Carreiro da Silva',
    }

errors = {
    "Marcelo Saragoza": "Marcelo Saragosa",
    "Lubis Kubik": "Lubos Kubik",
    "Abusuku Ubukusumo": "Ubusuku Ubukusumo",
    "Steven Keel": "Stephen Keel",
    "Alejandro Sequiera": "Alejandro Sequeira",
    "Patrick Iannia": "Patrick Ianni",
    "Guiseppe Galderisi": "Giuseppe Galderisi",
    "Jamie Clak": "Jamie Clark",
    "Albert Celades": "Alberto Celades",
    "JohnDeBrito": "John DeBrito",
    "Yari Allnut": "Yari Allnutt",
    "Tyronne Marshall": "Tyrone Marshall",
    "TyroneMarshall": "Tyrone Marshall",
    "Pablo Masteroeni": "Pablo Mastroeni",
    "Digitil Takawira": "Vitalis Takawira",
    "Digital Takawira": "Vitalis Takawira",
    "Abusuku Ubukusumo": "Ubusuku Abukusumo",
    "Teal Burnbury": "Teal Bunbury",
    "Diego Guttierez": "Diego Gutierrez",
    "Darryl Powell": "Daryl Powell",
    "Scott enedetti": "Scott Benedetti",
    "AJ DeLaGarza": "A.J. DeLaGarza",
    "Simon Elliot": "Simon Elliott",
    "Frankie Simek": "Frank Simek",
    "Hercules Gomez": "Herculez Gomez",
    "Gerell Elliot": "Gerell Elliott",
    "Esmundo Rodriquez": "Esmundo Rodriguez",
    "Alexei Korol": "Aleksey Korol",
    "Marcos Saragosa": "Marcelo Saragosa",
    "Andrew Wiederman": "Andrew Wiedeman",
    "Zack Kingsley": "Zach Kingsley",
    'Darly Powell': "Daryl Powell",
    "Jeay Heaps": "Jay Heaps",
    "Ian Hennessy": "Ian Hennessey",
    "Peter Villegas": "Petter Villegas",
    "Ted Chromopoulos": "Ted Chronopoulos",
    "Steve Yallop": "Frank Yallop",
    "Albert Munoz": "Alberto Munoz",
    'Vicent Figueroa': "Vicente Figueroa",
    'Jayson Boyce': "Jason Boyce",
    'Alex Prampin': 'Alan Prampin',
    'Jamie Moreno': "Jaime Moreno",
    'Tiyi Shipalane': 'Tiyiselani Shipalane',
    'Nicolas Henandez': "Nicolas Hernandez",
    'Niko Hernandez': "Nicolas Hernandez",
    'Nicolas Hernadez': "Nicolas Hernandez",
    'Julian Baudet': "Julien Baudet",
    'Jose Luis Burciaga Jr.': "Jose Burciaga",
    'Emilo Renteria': 'Emilio Renteria',
    'Tenwya Bonseu': "Tenywa Bonseu",
    'William DeOlivera': 'Willian Oliveira',
    'Orando Perez': "Orlando Perez",
    'Scott Buet Buete': "George Buete",
}

my_errors = {
    # Maybe my error
    "Garlon Cannon": "Garland Cannon",
    "Bryan Haynes": "Brian Haynes",
    
    }

mapping.update(errors)
mapping.update(my_errors)



